USE Xpenditure
GO

CREATE TABLE  USERS (
  ID INT IDENTITY PRIMARY KEY,
  USERNAME NVARCHAR(50) NOT NULL UNIQUE,
  PASSWORD NVARCHAR(30) NOT NULL ,
  ROLE INT,
  IS_ACTIVE INT, 
  CREATED_DATE DATE DEFAULT getdate(),
  UPDATED_DATE DATE DEFAULT getdate()
);


CREATE TABLE  USERS_DETAILS (
  ID INT IDENTITY PRIMARY KEY,
  U_ID INT NOT NULL  ,
  FNAME VARCHAR(30) NOT NULL,
  LNAME  VARCHAR(30),
  EMAILID NVARCHAR(40) NOT NULL,
  PHONENO BIGINT NOT NULL,
  ADDRESSLINE1 NVARCHAR(40),
  STREET NVARCHAR(40),
  PROVINCE NVARCHAR(30),
  ZIPCODE NVARCHAR(20),
  COUNTRY VARCHAR(40),
  IS_PREMIUM INT,
  CREATED_DATE DATE DEFAULT getdate(),
  UPDATED_DATE DATE DEFAULT getdate(),
  UPDATED_BY INT
    
	CONSTRAINT fk_USERS_DETAILS_USERS
		FOREIGN KEY (U_ID)
		REFERENCES USERS (ID),
	CONSTRAINT fk_USERS_DETAILS_UPDATEUSER
		FOREIGN KEY (UPDATED_BY)
		REFERENCES USERS (ID)
);


CREATE TABLE  ROLES (
  ID INT IDENTITY PRIMARY KEY,
  ROLESNAME VARCHAR(20) NOT NULL ,
  ROLESDESC VARCHAR(20),
  CREATED_DATE DATE DEFAULT getdate()
);

	ALTER TABLE USERS ADD CONSTRAINT fk_ROLES_USERS FOREIGN KEY (ROLE) REFERENCES ROLES (ID);

CREATE TABLE  CATEGORY (
  ID INT IDENTITY PRIMARY KEY,
  NAME VARCHAR(20) UNIQUE NOT NULL ,
  CREATED_BY INT,
  CREATED_DATE DATE DEFAULT getdate(),
  UPDATED_BY INT,
  UPDATED_DATE DATE DEFAULT getdate(),
  REMARKS NVARCHAR(50)

	CONSTRAINT fk_CATEGORY_CREATEUSER
		FOREIGN KEY (CREATED_BY)
		REFERENCES USERS (ID),
	CONSTRAINT fk_CATEGORY_UPDATEUSER
		FOREIGN KEY (UPDATED_BY)
		REFERENCES USERS (ID)
);

CREATE TABLE EXPENSE(
 ID INT IDENTITY PRIMARY KEY,
 CAT_ID INT NOT NULL,
 AMOUNT DECIMAL(7,2) NOT NULL,
 PAYEMNT_METHOD NVARCHAR(20) NOT NULL DEFAULT 'CASH',
 CREATED_BY INT,
 DESCRIPTION NVARCHAR(250),
  CREATED_DATE DATE DEFAULT getdate(),
  UPDATED_BY INT,
  UPDATED_DATE DATE DEFAULT getdate(),

  CONSTRAINT fk_EXPENSE_CREATEUSER
    FOREIGN KEY (CREATED_BY)
    REFERENCES USERS (ID),
	 CONSTRAINT fk_EXPENSE_UPDATEUSER
    FOREIGN KEY (UPDATED_BY)
    REFERENCES USERS (ID),
	CONSTRAINT fk_EXPENSE_CATEGORY
    FOREIGN KEY (CAT_ID)
    REFERENCES CATEGORY (ID),
);

CREATE TABLE  PREMIUM_USERS (
  ID INT IDENTITY PRIMARY KEY,
  USERID INT NOT NULL UNIQUE ,
  PASSWORD NVARCHAR(30) NOT NULL ,
  ROLES INT,
  SUBSCRIPTION_DATE DATE DEFAULT getdate(),
  START_DATE DATE,
  END_DATE DATE,
  IS_REPEAT INT,
  CREATED_DATE DATE DEFAULT getdate()

	CONSTRAINT fk_PREMIUM_USERS_USERS
    FOREIGN KEY (USERID)
    REFERENCES USERS (ID)
);


CREATE TABLE PAYMENT (
	ID INT IDENTITY PRIMARY KEY,
	TRANS_ID VARCHAR(40) UNIQUE,
	USERID INT,
	PAYMENT_METHOD VARCHAR(20) NOT NULL,
	AMOUNT INT,
	ACCOUNT_NUM INT NOT NULL,
	BANK_NAME CHAR(20) NOT NULL,
	BRANCH_NAME VARCHAR(30), 
	PAYMENT_STATUS CHAR(3),
	CONSTRAINT fk_PAYMENT_PREMIUM_USERS
    FOREIGN KEY (USERID)
    REFERENCES PREMIUM_USERS (ID)
);

ALTER TABLE EXPENSE ADD EXPENSE_DATE DATE NOT NULL DEFAULT GETDATE();


CREATE TABLE NOTIFICATION (
    ID INT IDENTITY,
	U_ID INT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DUE_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(MAX),
	CREATED_BY INT,
	CREATED_DATE DATE DEFAULT getdate(),
	UPDATED_BY INT,
	UPDATED_DATE DATE DEFAULT getdate(),
  
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY (ID), 
	CONSTRAINT fk_NOTIFICATION_USERS
    FOREIGN KEY (U_ID)
    REFERENCES USERS (ID),
	  CONSTRAINT fk_NOTIFICATION_CREATEUSER
    FOREIGN KEY (CREATED_BY)
    REFERENCES USERS (ID),
	 CONSTRAINT fk_NOTIFICATION_UPDATEUSER
    FOREIGN KEY (UPDATED_BY)
    REFERENCES USERS (ID),
);


INSERT INTO ROLES(ROLESNAME, ROLESDESC) VALUES('USER', 'normal user'); 
INSERT INTO ROLES(ROLESNAME, ROLESDESC) VALUES('ADMIN', 'admin user'); 